authors:
  mstrohl:
    name: Matthieu STROHL
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/16894230?v=4
    url: https://github.com/mstrohl
  test1:
    name: Alex Voss
    description: Community support
    avatar: https://avatars.githubusercontent.com/u/16894230?v=4
    url: https://github.com/test1
